"""create test tables

Revision ID: 08bb2f646765
Revises: 04e12ee1c05d
Create Date: 2025-04-01 15:19:27.254480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08bb2f646765'
down_revision: Union[str, None] = '04e12ee1c05d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books_test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('isbn', sa.String(length=20), nullable=True),
    sa.Column('cover_id', sa.Integer(), nullable=True),
    sa.Column('first_publish_year', sa.Integer(), nullable=True),
    sa.Column('open_library_key', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('open_library_key')
    )
    op.create_index(op.f('ix_books_test_id'), 'books_test', ['id'], unique=False)
    op.create_index(op.f('ix_books_test_isbn'), 'books_test', ['isbn'], unique=False)
    op.create_index(op.f('ix_books_test_title'), 'books_test', ['title'], unique=False)
    op.create_table('users_test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clerk_user_id', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clerk_user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_test_id'), 'users_test', ['id'], unique=False)
    op.create_table('user_book_test',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books_test.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users_test.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'book_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_book_test')
    op.drop_index(op.f('ix_users_test_id'), table_name='users_test')
    op.drop_table('users_test')
    op.drop_index(op.f('ix_books_test_title'), table_name='books_test')
    op.drop_index(op.f('ix_books_test_isbn'), table_name='books_test')
    op.drop_index(op.f('ix_books_test_id'), table_name='books_test')
    op.drop_table('books_test')
    # ### end Alembic commands ###
