"""create users test table

Revision ID: 18399932700b
Revises: 746ce1ed2537
Create Date: 2025-04-01 15:51:06.968019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18399932700b'
down_revision: Union[str, None] = '746ce1ed2537'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('genres', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_genres_name', table_name='genres')
    op.create_unique_constraint(None, 'genres', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'genres', type_='unique')
    op.create_index('ix_genres_name', 'genres', ['name'], unique=True)
    op.alter_column('genres', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
