"""Added books table

Revision ID: 3547ef964b41
Revises: 2fd1da5a06ef
Create Date: 2025-04-01 00:32:38.473458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3547ef964b41'
down_revision: Union[str, None] = '2fd1da5a06ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_authors_id', table_name='authors')
    op.drop_index('ix_authors_name', table_name='authors')
    op.drop_table('authors')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('open_library_key', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='authors_pkey'),
    sa.UniqueConstraint('open_library_key', name='authors_open_library_key_key')
    )
    op.create_index('ix_authors_name', 'authors', ['name'], unique=False)
    op.create_index('ix_authors_id', 'authors', ['id'], unique=False)
    # ### end Alembic commands ###
