"""Add Genre model and relationship with Onboarded_User

Revision ID: 62d5e6adf6b4
Revises: 49397a038a36
Create Date: 2025-03-19 19:32:39.209519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62d5e6adf6b4'
down_revision: Union[str, None] = '49397a038a36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
