"""Add book_genres association table

Revision ID: 931a897445df
Revises: da9a3f40bee6
Create Date: 2025-03-25 23:02:40.447063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '931a897445df'
down_revision: Union[str, None] = 'da9a3f40bee6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'genre')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('genre', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
