"""initial

Revision ID: c74859b55274
Revises: 
Create Date: 2025-04-01 23:15:19.562386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c74859b55274'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books_test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('isbn', sa.String(length=20), nullable=True),
    sa.Column('cover_id', sa.Integer(), nullable=True),
    sa.Column('first_publish_year', sa.Integer(), nullable=True),
    sa.Column('open_library_key', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('open_library_key')
    )
    op.create_index(op.f('ix_books_test_id'), 'books_test', ['id'], unique=False)
    op.create_index(op.f('ix_books_test_isbn'), 'books_test', ['isbn'], unique=False)
    op.create_index(op.f('ix_books_test_title'), 'books_test', ['title'], unique=False)
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_genres_id'), 'genres', ['id'], unique=False)
    op.create_table('users_test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clerk_user_id', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clerk_user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_test_id'), 'users_test', ['id'], unique=False)
    op.create_table('onboarded_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_onboarded_users_id'), 'onboarded_users', ['id'], unique=False)
    op.create_table('user_book_test',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books_test.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users_test.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'book_id')
    )
    op.create_table('onboarded_user_genres',
    sa.Column('onboarded_user_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.ForeignKeyConstraint(['onboarded_user_id'], ['onboarded_users.id'], ),
    sa.PrimaryKeyConstraint('onboarded_user_id', 'genre_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('onboarded_user_genres')
    op.drop_table('user_book_test')
    op.drop_index(op.f('ix_onboarded_users_id'), table_name='onboarded_users')
    op.drop_table('onboarded_users')
    op.drop_index(op.f('ix_users_test_id'), table_name='users_test')
    op.drop_table('users_test')
    op.drop_index(op.f('ix_genres_id'), table_name='genres')
    op.drop_table('genres')
    op.drop_index(op.f('ix_books_test_title'), table_name='books_test')
    op.drop_index(op.f('ix_books_test_isbn'), table_name='books_test')
    op.drop_index(op.f('ix_books_test_id'), table_name='books_test')
    op.drop_table('books_test')
    # ### end Alembic commands ###
