"""Add detailed Book model and relationship with Onboarded_User

Revision ID: d4b70836b44b
Revises: 62d5e6adf6b4
Create Date: 2025-03-19 19:36:12.709187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4b70836b44b'
down_revision: Union[str, None] = '62d5e6adf6b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
